CXX = g++
CXXFLAGS = -Wall -O -std=c++14 `pkg-config opencv4 --cflags`
LDFLAGS = `pkg-config opencv4 --libs`

all: show_image  show_movie split_movie

clean:
	rm -rf show_image show_movie split_movie *.o *~

show_image:

show_movie:

split_movie:
